AZURE_LOCATION: 'westeurope'
RESOURCE_NAME_PREFIX: 'ase-eslz'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-eslz-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'repalce me in repo secrets'
CICD_AGENT_TYPE: 'github'
